services:
  RestaurantOrderManagementApplication:
    container_name: wasabi-RestaurantOrderManagementApplication
    depends_on: []
    env_file: /Users/user/Desktop/RestaurantOrderManagementApplication/wasabi/local.env
    extra_hosts:
    - practo.local:172.17.0.1
    - RestaurantOrderManagementApplication.practo.local:172.17.0.1
    image: wasabi.practo.local/restaurantordermanagementapplication
    ports:
    - 8080:8080
    profiles:
    - app
    - RestaurantOrderManagementApplication
    stdin_open: true
    tty: true
    volumes:
    - source: /Users/user/Desktop/RestaurantOrderManagementApplication/src
      target: /www/app/src
      type: bind
